### PR TITLE
Pulled new vendor library versions

### PR DESCRIPTION
**Pull request by python-42**

### CODE REVIEW

**Comment by pordonj** [comment]
@python-42 are there any features you are specifically pulling these for? i saw something about bugs in one of the rev updates

**Comment by python-42** [comment]
I pulled the YAGSL one because it cleaned up the log messages when simulating slightly, and I just pulled all of them when I did that. If we are worried about stability with the new ones we can probably hold off on updating.

**Comment by pordonj** [comment]
Let's just update yagsl for now

**Comment by python-42** [comment]
I feel the we don't really have time to throughly test everything related to updating libraries right now so I am going to close this. We can come back another time.

**Pull request closed without merging**
